name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 701251269124.dkr.ecr.ap-south-1.amazonaws.com/nginx-repro
      - name: Build Docker image
        run: |
          docker build -t my-ncr .
      - name: Tag Docker image
        run: |
          docker tag my-ncr:latest 701251269124.dkr.ecr.ap-south-1.amazonaws.com/nginx-repro:latest
      - name: Push Docker image to ECR
        run: |
          docker push 701251269124.dkr.ecr.ap-south-1.amazonaws.com/nginx-repro:latest
