name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Send notification on success
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: prerna.muz2000@gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Build Success - ${{ github.repository }}
        body: |
          Build succeeded for ${{ github.repository }}.
          Commit: ${{ github.sha }}
        to: prerna.muz2000@gmail.com
        from: ${{ secrets.MAIL_USERNAME }}

    - name: Send notification on Alert
      if: Alert()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: prerna.muz2000@gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Build Failed - ${{ github.repository }}
        body: |
          Build failed for ${{ github.repository }}.
          Commit: ${{ github.sha }}
        to: prerna.muz2000@gmail.com
        from: ${{ secrets.MAIL_USERNAME }}
