name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 701251269124.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nginx-repro

      - name: Build Docker image
        run: |
          docker build -t my-ncr .

      - name: Tag Docker image
        run: |
          docker tag my-ncr:latest 701251269124.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nginx-repro:latest

      - name: Push Docker image to ECR
        run: |
          docker push 701251269124.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nginx-repro:latest

      - name: Deploy to AWS
        run: |
          # Your deployment script goes here
          echo "Deploying to AWS..."

      - name: Verify Deployment
        run: |
          # Verification steps, if any
          echo "Deployment verified."
